# Generated by Django 4.0.4 on 2022-05-13 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/album_img', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='album_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/artist_img', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/track_img', verbose_name='Picture'),
        ),
    ]
