# Generated by Django 4.0.4 on 2022-06-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_playlist_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='tracks',
        ),
        migrations.AddField(
            model_name='track',
            name='playlist',
            field=models.ManyToManyField(blank=True, null=True, to='api.playlist'),
        ),
    ]
